eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
 
otel:
  exporter:
    otlp:
      endpoint: http://otel-collector:4317
      protocol: grpc
 
management:
  tracing:
    sampling:
      probability: 1.0
        
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus
        
      
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

    tags:
      application: ${spring.application.name}          
   


   


logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId},correlationId=%X{correlationId}]"

 

    
    
