spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/servicepayment
    username: root
    password: rootdocker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      override-none: true  
   
  #web:
    #cors:
     # allowed-origins: none  
     
  security:
    oauth2:
      resourceserver:
        jwt:
          # For HS256 demo. In prod, prefer JWK set URI / public key.
          secret-key: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
     
    
    
  kafka:
   bootstrap-servers: localhost:9092
   consumer:
     group-id: order-service
     auto-offset-reset: earliest
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     properties:
       spring.json.trusted.packages: com.microtest.event
   producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
 

#logging:
 # level:
  #  org.springframework.security: DEBUG


resilience4j:

  circuitbreaker:
    instances:
      paymentService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException

  retry:
    instances:
      paymentService:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException

  timelimiter:
    instances:
      paymentService:
        timeoutDuration: 2s

app:
  kafka:
    topic:
      order: orders-topic3
      ordercreate: orders-create
      partition: 3
      replicate: 1
      paymentSuccess: payment-success
      paymentFailed: payment-failed
    dlt:
      order: orders-topic3-dlt
      ordercreate: orders-create-dlt
      partition: 3
      replicate: 1  
      
      
   

custom:
 msg: Good Study 
 
payment:
  service.url : http://localhost:8081/ 
  
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
  
server:
 port: 8082
 #address: 0.0.0.0 
 
 
