spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/serviceorder
    username: root
    password: rootdocker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
        
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      override-none: true    
         


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: tester
          # For HS256 demo. In prod, prefer JWK set URI / public key.
          secret-key: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  

jwt:
 access:
  secret: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
  expiration: 9000   # 15 min +
 refresh:
  secret: MysuperSecretKeyForJWT123456789009876hd7532dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
  expiration: 604800  # 7 days
 roles:
 admin: ROLE_ADMIN
 user: ROLE_USER
 
 

custom:
 msg: Good Study
 
  
  
server:
 port: 8083
 #address: 0.0.0.0

